### PR TITLE
Add Dask

### PR DESCRIPTION
**Pull request by mrocklin**
This adds Dask to the Python 3 statement.

One question: I noticed that all of the images here are PNG.  I uploaded an SVG (this just happens to be the most convenient for me at the moment) but I'd be happy to convert it as well.

### CODE REVIEW

**Comment by mrocklin** [comment]
I've asked for a few other Dask maintainers to +1 this PR to build authority behind it.

**Comment by jrbourbeau** [comment]
+1 from me, thanks for adding this @mrocklin!

**Comment by TomAugspurger** [comment]
+1

**Comment by hugovk** [comment]
SVG v. PNG: whichever is smallest! See https://github.com/python3statement/python3statement.github.io/issues/200. So probably SVG. :)

**Comment by mrocklin** [comment]
I'm definitely in favor of SVG generally.  When I ran Jekyll locally I did find that the logo was quite small, so there might need to be a small CSS change somewhere.

**Comment by takluyver** [comment]
There's an automatically generated preview as well: https://deploy-preview-239--python3statement.netlify.com/

Inspecting the icon, it looks like we set `max-width` and `max-height` CSS properties, but the size the SVG 'wants' to be is smaller than that. I guess that's something that can be set in the SVG file itself? I don't think we should set `height` and `width` for all logos, because that stretches them to fill the bounding box.

**Comment by Carreau** [comment]
We can sett a `min-width: 100px` on the wrapping `<li>`, that seem to do the trick; and affect mostly the dask logo.

**Comment by Carreau** [comment]
Let's get that in; we can refine. 

Thanks.

**Comment by hugovk** [comment]
Putting dask.svg through https://svgtopng.com:

```
 24K dask.png
2.3K dask.svg
```

After squashing:

```
  12K dask.png
 2.3K dask.svg
```

Big win for SVG.

**Comment by takluyver** [comment]
Now we just need pngtosvg.com! :-P

**Comment by Carreau** [comment]
Well svgs can include rasterized data right ? 
Otherwise it's pretty easy to make lots of colored squares in SVG :-)

**Pull request merged**
