### PR TITLE
Apache MXNet (Incubating) pledge

### PR DESCRIPTION
**Pull request by szha**
mxnet community has discussed and agreed to drop python2 support and fully adopt python3. https://lists.apache.org/thread.html/e7beecddf67731314582c0c8d60e939987718a98b47fee47c2dcc753@%3Cdev.mxnet.apache.org%3E

### CODE REVIEW

**Comment by szha** [comment]
ping @takluyver @nschloe

**Comment by takluyver** [comment]
Thanks. Has the community around mxnet also discussed putting its name to this statement? Some projects are planning to require Python 3, but still prefer not to sign this statement, and we don't want anyone to be surprised to see their project on the list.

**Comment by szha** [comment]
@takluyver yes it was brought up in discussion in the community and is agreed on.

**Comment by takluyver** [comment]
Can you run `scripts/squash-images.sh` on the logo? This will resize and compress it to save bandwidth.

**Comment by szha** [comment]
Done

**Comment by szha** [comment]
@takluyver this PR should be ready now.

**Comment by takluyver** [comment]
Thanks

**Pull request merged**
