### PR TITLE
Add CherryPy project

### PR DESCRIPTION
**Pull request by jaraco**

### CODE REVIEW

**Comment by mscuthbert** [comment]
Confirmed that requester is the largest contributor to the project since 2013 and has approval from other major contributor.

**Comment by Carreau** [comment]
Awesome, thanks !

**Comment by mscuthbert** [comment]
Confirmed that position in list is appropriate given number of stars.  Merging.

**Comment by mscuthbert** [comment]
"Merging" -- well not if Carreau doesn't beat me to it.  :-)

**Pull request merged**
