### PR TITLE
Add angr

### PR DESCRIPTION
**Pull request by ltfish**

### CODE REVIEW

**Comment by Carreau** [comment]
Awesome ! Thanks !

(Confirm Author is main contributor of Angr)

**Comment by Carreau** [comment]
When dropping Python 2 don't forget to read the [practicalities](http://python3statement.org/practicalities/) section, which explain how to set python_requires to tell pip not to install angr 8 on Python 2

Feel free to ping up on the PR that does it if you want an extra pair of eyes !

**Comment by ltfish** [comment]
That was a fast merge... Thanks a lot!

We will read the practicalities section.

**Comment by Carreau** [comment]
I've made a couple of comments on https://github.com/angr/angr/pull/1210 as well that give you the crux of practicalities. And that's quite a big PR ! Enjoy Python 3 !

**Comment by Carreau** [comment]
> That was a fast merge

Well it was pretty simple, and it's always good to have one less thing in the todo list :-)

**Comment by ltfish** [comment]
FYI This is the actual issue that tracks our entire Python 3 transition process: https://github.com/angr/angr/issues/1209

With more big PRs :)

**Pull request merged**
