### PR TITLE
Add FontTools project with icon and timeline

### PR DESCRIPTION
**Pull request by anthrotype**
Thanks for this initiative!

FontTools is a python library to manipulate font files, with a long history (the project started almost 20 years ago in 1999) and a relatively large community of contributors.

https://github.com/fonttools/fonttools

I wasn't sure where to put it in the list (we have 1,455 stars on github).
Anyway, we're happy to simply be here :)

I'll look forward to a world without python2.7 :+1: :snake:

### CODE REVIEW

**Comment by miguelsousa** [comment]
@anthrotype "libarary" as well

**Comment by anthrotype** [comment]
oh thanks Miguel :)

**Comment by takluyver** [comment]
Thanks! The projects are roughly ordered by Github stars; it looks like your tally would put you between Nikola (1586) and Pythran (997). It looks like some of them have got a bit out of order as projects get more stars, but that's still about the right spot.

Have you had a discussion with the other core developers of the project about signing up to the statement?

**Comment by anthrotype** [comment]
Ok, I'll put in that order then.
Yes, we discussed the timeline of py2.py3 support in https://github.com/fonttools/fonttools/issues/765
I'm the maintainer of project.

**Comment by anthrotype** [comment]
done!

**Comment by takluyver** [comment]
Thanks, welcome aboard!

**Pull request merged**
