### PR TITLE
Add legend for timeline.

### PR DESCRIPTION
**Pull request by Carreau**
screen shot 2016-05-20 at 14 12 17

### CODE REVIEW

**Comment by takluyver** [comment]
Looks good, but I'd make the wording a bit shorter, and start each from "Version compatible with..."

**Comment by asmeurer** [comment]
You don't even need "version". Just "Compatible with Python 2 and Python 3" and "Compatible with Python 3 only"

**Comment by Carreau** [comment]
Done.

**Comment by takluyver** [comment]
I wouldn't say 'Project', because it's the release, not the project, that is compatible or not. I'd either say 'version compatible ...', or as Aaron suggests, just 'compatible...'.

**Comment by Carreau** [comment]
Done.

**Pull request merged**
