### PR TITLE
add pytorch to list

### PR DESCRIPTION
**Pull request by soumith**
If you're adding a project to the Python 3 statement, please ensure you have:

- [x] Discussed dropping Python 2 support with all maintainers
- [x] Discussed signing the statement with all maintainers
- [x] Added a suitable logo if the project has one
  - [x] Approximately square logos generally fit better than banners
  - [x] Compressed the logo to save bandwidth (run `scripts/squash-images.sh` on it)
- [x] Checked the Netlify preview made from the pull request

### CODE REVIEW

**Comment by soumith** [comment]
fyi, we've discussed it at https://github.com/pytorch/pytorch/issues/23795 and we're (pytorch maintainers) are all good on this.

But sure, I can ping you in a couple of days.

**Comment by takluyver** [comment]
It looks like there hasn't been much discussion about signing the statement specifically: it's only suggested by @hugovk's post about a month ago, and then there are no responses until you mentioned this PR today.

It doesn't seem likely that anyone will object, but we've had at least one project that resolved to drop Python 2 support but not to sign this statement, so I take care not to merge any new signatures too quickly. :-)

**Comment by takluyver** [comment]
(Obviously if I've overlooked some discussion about the statement, please correct me!)

**Comment by soumith** [comment]
pinging after two days :)

> (Obviously if I've overlooked some discussion about the statement, please correct me!)

Yes, sorry the maintainers also discussed it on our private slack channel but that's not publicly visible info.

**Comment by takluyver** [comment]
Thanks, and welcome aboard! :-)

**Pull request merged**
