### PR TITLE
Auto-restar

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by Carreau** [comment]
And as you can see it get the url from within the comments if there is one.

```
diff --git a/_sections/30-projects.md b/_sections/30-projects.md
index c629e0f..0f9045e 100644
--- a/_sections/30-projects.md
+++ b/_sections/30-projects.md
@@ -13 +13 @@ These projects pledge to drop Python 2 support in or before 2020.
-- [![](assets/tensorflow.png)TensorFlow](https://www.tensorflow.org/) <!-- url:https://github.com/tensorflow/tensorflow -->
+- [![](assets/tensorflow.png)TensorFlow](https://www.tensorflow.org/) <!-- url:https://github.com/tensorflow/tensorflow sg:128577 -->

commit b0731df74af425bdabd968ec22af576aadb271fe
Author: Matthias Bussonnier <mbussonnier@ucmerced.edu>
Date:   Thu May 30 13:37:29 2019 -0700

    add tensorflow url

diff --git a/_sections/30-projects.md b/_sections/30-projects.md
index a4e0fc4..c629e0f 100644
--- a/_sections/30-projects.md
+++ b/_sections/30-projects.md
@@ -13 +13 @@ These projects pledge to drop Python 2 support in or before 2020.
-- [![](assets/tensorflow.png)TensorFlow](https://www.tensorflow.org/)
+- [![](assets/tensorflow.png)TensorFlow](https://www.tensorflow.org/) <!-- url:https://github.com/tensorflow/tensorflow -->
```

**Comment by Carreau** [comment]
I now added a script that reorder consecutive line groups with `sg:<a-number>`.

**Comment by Carreau** [comment]
Added the url for a number of other project, auto-recomputed the number of stars and reordered them. 

A couple had no - or irrelevant – url. I assigned them a stargazer count to not have them move too much in the list.

**Comment by mscuthbert** [comment]
I have some more URLs for others -- I'll close my PR and after this is merged (it seems the right way to go), I'll make a PR to add the urls and rerun the script.  Thanks!

**Comment by Carreau** [comment]
OK, let's merge and iterate to avoid further conflicts then !

Thanks !

**Comment by takluyver** [comment]
Belatedly seeing this, but cool :-)

**Pull request merged**
