### PR TITLE
add gluonnlp to the py3 pledge

### PR DESCRIPTION
**Pull request by szha**
add gluonnlp to the py3 pledge

### CODE REVIEW

**Comment by szha** [comment]
ping @takluyver @nschloe

**Comment by nschloe** [comment]
@szha Please don't tag me.

**Comment by takluyver** [comment]
I'm guessing from the URL that this is covered by the agreement for MXnet you already described in #251?

**Comment by szha** [comment]
@takluyver this is a separate community project and not part of the mxnet project.

**Comment by takluyver** [comment]
OK, and have any other maintainers of gluonnlp agreed about requiring Python 3 and about adding the project to the statement?

**Comment by szha** [comment]
Yes, see https://github.com/dmlc/gluon-nlp/issues/721

**Comment by szha** [comment]
@takluyver this PR should be ready now.

**Comment by takluyver** [comment]
Thanks. I was on holiday, that's why I wasn't merging things.

**Comment by szha** [comment]
@takluyver thanks! hope you had a good time

**Pull request merged**
