### PR TITLE
Add Sphinx

### PR DESCRIPTION
**Pull request by shimizukawa**
Sphinx will drop support for Python 2.7 on 2019-03-10. I'm a maintainer of Sphinx, here's links to documentation and the relevant issues:

* http://www.sphinx-doc.org/en/master/changes.html (2.0.0b1)
* https://github.com/sphinx-doc/sphinx/pull/5342

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! Are the other Sphinx core maintainers on board with putting the project's name on this statement? We try to ensure that no-one is suprised by seeing their project listed on the statement.

You might want to use only the eye part of the logo - the way logos are displayed on the website works best with a roughly square shape. Up to you, but I think this looks a bit ugly:

Screenshot from 2019-07-07 13-40-49

Finally, once you're happy with the logo, please run `scripts/squash-images.sh` on it to resize and compress it to save bandwidth.

Thanks!

**Comment by shimizukawa** [comment]
OK, I'll update it soon.

**Comment by shimizukawa** [comment]
> Are the other Sphinx core maintainers on board with putting the project's name on this statement? We try to ensure that no-one is suprised by seeing their project listed on the statement.

@tk0miya knows this.
@birkenfeld, @jfbu, @stephenfin, @lehmannro, @DasIch, @jacobmason, @TimKam, @RobRuana: there's no problem posting Sphinx as Python2 support termination?

> You might want to use only the eye part of the logo

Updated. It looks fine.
https://deploy-preview-247--python3statement.netlify.com/

> please run scripts/squash-images.sh on it to resize and compress it to save bandwidth.

Done!

**Comment by birkenfeld** [comment]
Go ahead :)

**Comment by takluyver** [comment]
Thanks. I'll give it another day or so to ensure that all the people you tagged have a chance to see it, then this can be merged.

**Comment by stephenfin** [comment]
All good from my end too

**Comment by mscuthbert** [comment]
Just to note since the date and tense in the initial posting was a little unclear: Sphinx 2.0 (released in March of this year) already dropped Python 2.7 support.

**Comment by takluyver** [comment]
Thanks all!

**Pull request merged**
