### PR TITLE
add TatSu to projects and timeline

### PR DESCRIPTION
**Pull request by apalala**
Tatsu is a PEG/Packrat parser generator in Python

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! Projects are arranged by Github stars, so I think you can put yourself between pymeasure and chaquopy.

(Confirmed that @apalala is the maintainer of TatSu)

**Comment by apalala** [comment]
Fixed the position in the list @takluyver!

**Comment by takluyver** [comment]
Thanks! Can you shrink the image down to a smaller size? You should be able to run `scripts/squash-images.sh`.

**Comment by apalala** [comment]
More assets than the one I posted seem to have been shrunk. Is that OK?

**Comment by takluyver** [comment]
I'm guessing this might be teething problems because you opened your pull request before we resized the other images. I'll manually rebase and merge this branch.

**Comment by takluyver** [comment]
Done by commit 8155bf227a0bcadb2c9c00cb464a68363cd955cf (and a few preceding commits).

**Pull request closed without merging**
