### PR TITLE
Add kivy to project list

### PR DESCRIPTION
**Pull request by matham**
This adds Kivy to the project list.

### CODE REVIEW

**Comment by Carreau** [comment]
Great ! Awesome ! I'm giving a talk to PyBay mid august to speak about the Python 3 statement, it's great to see the list growing. 

For archival purpose, I verified that @matham is a core contributor of Kivy, still feel free to link to a discussion (if available) where the decision to stop Python 2 support was taken it is often a good resource for future project to look at. 

Please also have a look at our [practicalities](http://www.python3statement.org/practicalities/) section to make sure to disrupt python 2 users the least, and contribute feedback. We'll be happy to give you commit right to the repository if you desire.

**Comment by dessant** [comment]
@Carreau, thanks for merging! I can confirm the decision to stop Python 2 support in Kivy, a draft of our plans can be seen here: https://github.com/kivy/kivy/wiki/Kivy-Python-2-Support-Timeline.

**Comment by matham** [comment]
Yeah, we had a private discussion on IRC so there's no record. It was mainly driven by my desire to use async with kivy :) 

Since we do a yearly release, so it makes sense to make our last py2 release 2019 and the subsequent release would be in 2020 so there's no need to make master py2 compat anymore after the 2019 release. 

I didn't want to add this to the timeline because our 2019 drop date is still estimated depending on how things are then. But we figured that around 2019 it'd become popular for open source projects to drop python 2 support so hopefully it wouldn't be too much of an issue for our users, especially given this early notice.

I hadn't noticed that the practicalities page was separate, but I don't really have much to add there. Our considerations was between having a LTS that supports py2 after 2019, but we didn't think we had the resources for that.

**Comment by Carreau** [comment]
> Yeah, we had a private discussion on IRC so there's no record. It was mainly driven by my desire to use async with kivy :)

I hear you!



> Since we do a yearly release, so it makes sense to make our last py2 release 2019 and the subsequent release would be in 2020 so there's no need to make master py2 compat anymore after the 2019 release.
> 
> I didn't want to add this to the timeline because our 2019 drop date is still estimated depending on how things are then. But we figured that around 2019 it'd become popular for open source projects to drop python 2 support so hopefully it wouldn't be too much of an issue for our users, especially given this early notice.

No worries, feel free to submit changes any times you like. 

> I hadn't noticed that the practicalities page was separate, but I don't really have much to add there. Our considerations was between having a LTS that supports py2 after 2019, but we didn't think we had the resources for that.

Sure, by 2019, hopefully pep517 will be implemented and we'll have more to say. The goal being to warn user early (especially python 2 users) to be careful on upgrade. 

Thanks !

**Pull request merged**
