### PR TITLE
Add Bokeh to the list

### PR DESCRIPTION
**Pull request by brettcannon**
Dropping support in the second half of 2019.

### CODE REVIEW

**Comment by Carreau** [comment]
That's awesome ! I guess you cold put it in the sections with the logo. Bokeh has a nice logo. 

Don't forget to set the `python_requires` metadata in `setup.py`

I'll wait for @bryevdv +1.

**Comment by bryevdv** [comment]
+1 ! Thanks @brettcannon

**Comment by brettcannon** [comment]
I expect @bryevdv or someone will eventually add the logo, but I was talking with Bryan about this in a call and so doing the edit immediately in the GitHub web UI was too easy to not just do it. 😄

**Comment by bryevdv** [comment]
Not sure if it's easier to make a new PR for the logo or continue here. In case its the latter, here is the logo:

logo

**Comment by Carreau** [comment]
Merging for now I'll add the logo later.

**Comment by Carreau** [comment]
Thansk !

**Pull request merged**
