### PR TITLE
Add folium to participating projects

### PR DESCRIPTION
**Pull request by Conengmo**
The next release of folium will be the last to support Python 2. See https://github.com/python-visualization/folium/pull/1087.

### CODE REVIEW

**Comment by hugovk** [comment]
The projects are sorted roughly by GitHub stars. You could move this above better-exceptions.

**Comment by takluyver** [comment]
Thanks! Pinging @ocefpaf to be aware that Folium is being added to this list.

**Comment by ocefpaf** [comment]
> Thanks! Pinging @ocefpaf to be aware that Folium is being added to this list.

Thanks for the ping @takluyver. BTW, @Conengmo is the main `folium` dev now.

**Comment by takluyver** [comment]
Thanks! I could see that @Conengmo was most active on the repo recently, but I saw you were still merging their PRs.

**Comment by Conengmo** [comment]
We have a no self merging policy so I always appreciate Filipes checks :)

**Pull request merged**
