### PR TITLE
Compact list (wrap on 2 multiple lines) and prepare for images.

### PR DESCRIPTION
**Pull request by Carreau**
Cf #17 

--- 
With that you can "just" precede the project name with a `` and it should work, as long as the logo is available of course.

### CODE REVIEW

**Comment by takluyver** [comment]
Screenshot? I'm not quite sure what you mean. And can we try sticking some logos in to see what it looks like?

**Comment by Carreau** [comment]
screen shot 2016-06-22 at 14 24 46

Yes we can stick some logo. The jupyter logo does not look good on this kind of BG. We need one with whiter text/moon, or a white outline.

**Comment by Carreau** [comment]
Screenshot with logo. It definitively need refinement, but at least the layout is almost correct. 
screen shot 2016-06-22 at 14 32 58

**Comment by Carreau** [comment]
Tweaked design and color, Purple seemed really bad with many logo and made them black and white (except on hove) 

screen shot 2016-07-01 at 17 24 03
screen shot 2016-07-01 at 17 24 26

Or with color , what do you think ? 


screen shot 2016-07-01 at 17 25 32

**Comment by Carreau** [comment]
I need to reintroduce Xonsh.

**Comment by takluyver** [comment]
The light background is definitely better, and I think I like it with colours - logos designed for colour look a bit sad in grayscale.

**Comment by Carreau** [comment]
> The light background is definitely better, and I think I like it with colours - logos designed for colour look a bit sad in grayscale.

Done. Now in color and with Xonsh.

**Comment by takluyver** [comment]
Alright, let's merge it and see how we like it :-)

**Comment by Carreau** [comment]
So how you like it ?

**Comment by takluyver** [comment]
It's good. I wonder about switching the section colours around so the logos are on a white background - that's how most of them are designed to exist. But that's not urgent.

**Pull request merged**
