### PR TITLE
Squash images (pngcrush version)

### PR DESCRIPTION
**Pull request by hugovk**
For #165 and #200.

Like https://github.com/python3statement/python3statement.github.io/pull/201 but with lossless pngcrush instead of lossy pngquant.

| What | How big | Percent of original |
| - | -: | -: |
| master | 3,230,356 bytes (3.4 MB on disk) | 100% | 
| after script | 1,423,814 bytes (1.5 MB on disk) | 44% | 

(Edit: updated after script sizes)

The `-brute` option doesn't save much space, but we're not time critical so might as well squeeze out the last few bytes.

| Option | Time | Size |
| - | -: | -: |
| With `-brute` | 1m30s | 1,423,814 bytes (1.5 MB on disk) for 62 items |
| Without `-brute` | 7s | 1,431,120 bytes (1.5 MB on disk) for 62 items |

(Edit: updated)

### CODE REVIEW

**Comment by takluyver** [comment]
How are you getting those sizes? I just checked out this branch, and I'm seeing about 1.5 MB of data in `assets`.

**Comment by hugovk** [comment]
Good question! I also see 1,423,814 bytes (1.5 MB on disk) now. 

I must have initially tested pngcrush without resizing first. I'll update with/without `-brute` values too.

**Comment by hugovk** [comment]
Updated, sorry for the confusion!

**Comment by takluyver** [comment]
Thanks!

As I'm not an expert in image processing, I'm inclined to go with the lossless compression for now (this PR). We can always swap in pngquant later if we need to squeeze the size even more. Does that sound reasonable to you?

**Comment by hugovk** [comment]
You're welcome!

Sounds perfectly reasonable, it's already a good saving.

**Comment by takluyver** [comment]
OK, thanks. I'm going to rebase the branch locally to cut out all the regenerations of the images, and make a couple of other manual tweaks.

**Comment by takluyver** [comment]
Continued & merged in #203.

**Pull request closed without merging**
