### PR TITLE
Add Numpy timeline

### LINKED ISSUE #89: Numpy timeline proposal
Just in case you missed it, and for documentation purposes:

https://mail.python.org/pipermail/numpy-discussion/2017-November/077341.html

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #89.

Based on https://github.com/numpy/numpy/blob/master/doc/neps/nep-0014-dropping-python2.7-proposal.rst.

### CODE REVIEW

**Comment by Carreau** [comment]
cc @njsmith

**Comment by rth** [comment]
For other projects the Python 3 support (or not) is liked to release numbers, while numpy's NEPS only specifies calendar period, but I guess not much can be done about it. The dates in the PR match the NEPS. It would  be good to have this online on the website.

**Comment by hugovk** [comment]
Is this good to merge?

**Comment by mscuthbert** [comment]
Looks good to me.  Merged

**Pull request merged**
