### PR TITLE
Add link to Python clock.

### LINKED ISSUE #26: Possible site to link to
http://pythonclock.org/

### PR DESCRIPTION
**Pull request by Carreau**
Closes #26

### CODE REVIEW

**Comment by takluyver** [comment]
I'm not convinced about that site. AFAIK, Python devs have just said 2020, so whoever made the site has just picked a date in 2020 to count down to. I don't think that spurious precision helps anyone.

**Comment by Carreau** [comment]
I'm 50/50, feel free to close, but close #26 as well then.

**Comment by takluyver** [comment]
OK, then I think I'm going to say that that's not quite the vibe we're going for.

**Comment by asmeurer** [comment]
In case you missed it, Guido endorsed this in his PyCon keynote. I do still agree with @takluyver that it's not the vibe we want, however.

**Comment by takluyver** [comment]
Thanks Aaron, I hadn't heard about that.

**Pull request closed without merging**
