### PR TITLE
Add Plyara name and link to list

### LINKED ISSUE #180: Add plyara
Greetings,

We released plyara 2.0.0 a few weeks ago. We have dropped support for python 2 and refactored everything for 3.6/3.7.

https://github.com/plyara/plyara

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Fixes #180 . @utkonos please review and confirm.

I could add you to the schedule, but I'll need to know more specifics and it seems its only used for larger projects with a large number of users or back-dependencies, since it takes up a lot of space on the page.

### CODE REVIEW

**Comment by utkonos** [comment]
No problem. We dropped 2 and release a 3-only version 2.0.0 on Feb 1, 2019.

**Comment by CAM-Gerlach** [comment]
@takluyver Opinion on adding another entry to the schedule?

**Comment by hugovk** [comment]
@CAM-Gerlach Should be fine, see https://github.com/python3statement/python3statement.github.io#add-timeline-information for info.

**Comment by CAM-Gerlach** [comment]
@hugovk Thanks, I do know how to do it :) (see #141 and #209 ) What I was asking was (as a followup to what I brought up with @takluyver previously) whether it was worthwhile to do for a project that doesn't really have the same order of magnitude of either direct users or other projects dependent on it as almost every other package on the list, particularly given one minimal schedule line takes up nearly the space that 4-5 logos do on the list above, and at much higher density.

**Comment by takluyver** [comment]
I have some concern over how big the timeline is getting (#46), but we haven't figured out any neat solution yet, and I don't want to randomly stop adding projects that want to be listed on there. So I'm happy for it to keep growing until someone has a better idea. ;-)

**Comment by takluyver** [comment]
Thanks

**Comment by CAM-Gerlach** [comment]
@takluyver !!!

**Comment by CAM-Gerlach** [comment]
@utkonos did not check and approve the timeline!

Again, @utkonos , what I've been asking you is

> how long have you supported Python 3 **before** you dropped Python 2 support, or with what approx release?

As (what I thought was) a temporary stopgap, I put in the date of your 1.2.0 release, listed as the first one of the community maintained ``plyara``, reasoning that was when a version was officially released fully supporting Python 3. Is that correct? Also, in addition to my previous question, is 2020-01-01 fine as an end date for 2.x for now, or do you have something more specific in mind? Thanks.

**Comment by takluyver** [comment]
Sorry, I'm trigger happy on the merge button today. Feel free to make another PR if it needs changing.

**Comment by CAM-Gerlach** [comment]
Np. @utkonos , just lmk if it needs any changes and I'll make them in a new PR. Thanks.

**Comment by utkonos** [comment]
I think I have answered this already. Here it is again: version 2.0.0 that
we released on February 1 was a rewrite of the project in python 3. We
decided to drop 2 support at that time.

**Comment by CAM-Gerlach** [comment]
> version 2.0.0 that we released on February 1 was a rewrite of the project in python 3

Ah, that's what I was looking for; thanks @utkonos . I'll just nix the ``Python 2 and 3 support`` component entirely, then.

**Pull request merged**
