### PR TITLE
Add Cartopy to projects list

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
@pelson @QuLogic I went ahead and created a draft PR for Cartopy, if you are interested in adding your name to the list. It will *not* be merged without your explicit review and approval, so please let us know if you might be interested. Thanks!

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm fine with this and the quicker the better, but I'm not really the one deciding these things.

**Comment by CAM-Gerlach** [comment]
Thanks @QuLogic . Is @pelson the one, or should I tag someone else?

**Comment by dopplershift** [comment]
Seems sane enough to me, all the PR here does is confirm we're dropping 2.7.

**Comment by CAM-Gerlach** [comment]
@takluyver This looks good to merge, then.

**Comment by CAM-Gerlach** [comment]
Thanks @dopplershift . Are you the one @QuLogic mentioned that "decides these things" and can speak on behalf of the project to approve this, or is that @pelson or someone else? If the latter, all we need is a quick signoff here and we should be good to merge. Thanks!

**Comment by dopplershift** [comment]
Well, I'm a core dev and we have @pelson's original word in scitools/cartopy#1186, so I would think that's good enough.

**Comment by CAM-Gerlach** [comment]
That seemed pretty conclusive to me (which is why I un-draft-PRed it). @takluyver ?

**Comment by takluyver** [comment]
Thanks, that's good enough for me. Can you try squashing the logo with `scripts/squash-images.sh` and see if it improves the file size?

**Comment by CAM-Gerlach** [comment]
@takluyver I'd already resized it to ~160 x 80, 1/4 of the size ``thumbnail-images.py`` does, and run ``optipng -o7`` on it as a matter of course (I was the one that originally suggested ``squash-images.sh`` be updated to use it). The additional savings from ``zm1-9`` are generally minuscule to nonexistent and takes an order of magnitude or more time to run, so I didn't bother with it. However, I ran ``optipng`` with that now just to see and it saved a further 100 bytes (0.4%), so I pushed up the new version.

**Comment by takluyver** [comment]
Yes, that would have been fine, thanks. I just saw the 24 KB and thought it seemed quite a lot for a small image. But I guess not all logos compress well.

**Comment by CAM-Gerlach** [comment]
@takluyver Probably had to do with the Lanczos downsampling I used by default, instead of nearest-neighbor (assuming I could get away with it) or something else simple. Due to its fundamental nature of the re-interpolation process, line art with a small number of discrete colors but sufficient high-frequency detail will often not compress nearly as well when downsampled, sometimes even to the point of being as large or even slightly *larger* than of not downsampled (after running through ``optipng``), due to the resulting patterns being less predictable/homogeneous for the PNG compression algorithms and the Lanzos transform resulting in many more discrete colors requiring more bits per pixel to store. I've since employed a more careful manual downsampling technique to mostly avoid this.

**Pull request merged**
