### PR TITLE
Add SunPy to list and timeline.

### PR DESCRIPTION
**Pull request by Cadair**
bring on the future... :D

### CODE REVIEW

**Comment by Cadair** [comment]
@sunpy/sunpy-board ping.

**Comment by Cadair** [comment]
@dpshelio @ehsteve @ayshih ping

**Comment by takluyver** [comment]
Thanks! :-)

**Comment by dpshelio** [comment]
Yay!!! and forget the past!!!!!

**Comment by ayshih** [comment]
> bring on the future... :D

The future scares me... =P

Is the 5-month/7-month stepping of releases what we intend (or is that a typo)?

**Comment by Cadair** [comment]
fixed

**Comment by Carreau** [comment]
Awesome !

I'll move you above Xonsh seeing the number of GitHub Stars.

**Comment by Cadair** [comment]
it's like we are important and stuff :p

**Pull request merged**
