### PR TITLE
Adding ESMValTool project

### PR DESCRIPTION
**Pull request by valeriupredoi**
Hey guys, adding our project to the list https://github.com/ESMValGroup/ESMValTool/ :beer:

### CODE REVIEW

**Comment by valeriupredoi** [comment]
also, super job in setting this one up! :beers:

**Comment by takluyver** [comment]
Thanks! Have you discussed adding the project to the statement with any other maintainers? We try to ensure that no-one is surprised to see their project on the list.

You may want to use just the globe part of the logo - the layout works best with roughly square logos rather than narrow rectangles ([see the preview](https://deploy-preview-259--python3statement.netlify.com/)). Up to you. Also, can you run `scripts/squash-images.sh` on the logo to compress it as small as possible?

**Comment by valeriupredoi** [comment]
Hi @takluyver cheers for getting back to me, yeah we have an open issue that all the ESMValTool core devs are aware of and they're all for it https://github.com/ESMValGroup/ESMValCore/issues/23 - could we please keep the full globe + name of the package since that's the official logo; I will run the squashing script now tho :beer: (apologies for the delayed reply, I was traveling yesterday)

**Comment by takluyver** [comment]
OK, thanks!

**Comment by valeriupredoi** [comment]
smashing! cheers, guys, we're proud to be there with the lot :beer:

**Pull request merged**
