### PR TITLE
Add python-gitlab

### PR DESCRIPTION
**Pull request by max-wittig**
If you're adding a project to the Python 3 statement, please ensure you have:

- [x] Discussed dropping Python 2 support with all maintainers
- [x] Discussed signing the statement with all maintainers
- [x] ~~Added a suitable logo if the project has one~~
  - [x] ~~Approximately square logos generally fit better than banners~~
  - [x] ~~Compressed the logo to save bandwidth (run `scripts/squash-images.sh` on it)~~
- [x] Checked the Netlify preview made from the pull request

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! The projects are ordered by stars count, so you can move it much further up the list - just after h5py, I think.

(Checked that @max-wittig is the main maintainer of python-gitlab)

**Comment by max-wittig** [comment]
@takluyver Thanks for the review. Order changed now.

**Comment by takluyver** [comment]
Thanks, and welcome aboard!

**Comment by max-wittig** [comment]
@takluyver Thank you. Looking forward to 2020-01-01 😄

**Pull request merged**
