### PR TITLE
Add Pelican to projects pledged to go Python 3-only

### PR DESCRIPTION
**Pull request by justinmayer**
If you're adding a project to the Python 3 statement, please ensure you have:

- [x] [Discussed](https://github.com/getpelican/pelican/issues/2645) dropping Python 2 support with all maintainers
- [x] [Discussed](https://github.com/getpelican/pelican/issues/2645#issuecomment-549971472) signing the statement with all maintainers
- [x] Added a suitable logo if the project has one
  - [x] Approximately square logos generally fit better than banners
  - [x] Compressed the logo to save bandwidth (run `scripts/squash-images.sh` on it)
- [x] Checked the Netlify preview made from the pull request

### CODE REVIEW

**Comment by justinmayer** [comment]
Preview looks good, so everything should be all set here. Many thanks for all your work on this endeavor, @takluyver! 👏

**Comment by takluyver** [comment]
Thanks! This all looks good to me. I'll leave it for a day or so, though, as I see your 'unless there are any objections' post was just a couple of hours ago. If I forget about it, please ping to remind me.

It's not just me - I've been clicking the merge button a lot lately, but @Carreau and @asmeurer did more to get the initiative off the ground, and several other people have contributed significantly.

**Comment by justinmayer** [comment]
Sincere apologies to @Carreau and @asmeurer for the oversight! Your work on this project is indeed much appreciated.

I've heard nothing but enthusiastic support among fellow Pelican Dev Team members for dropping Python 2, so I think it's safe to say that this PR can be merged. Many thanks for adding Pelican to the list! 😁

**Comment by takluyver** [comment]
Thanks!

**Pull request merged**
