### PR TITLE
Add Nengo to the project list

### PR DESCRIPTION
**Pull request by tbekolay**
We have a [PR to drop support](https://github.com/nengo/nengo/pull/1520) which will be merged in the next week or so.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks Trevor! The PR looks fine to me. I see you're the main maintainer of Nengo - are any other maintainers in agreement about putting the project's name on this statement?

**Comment by drasmuss** [comment]
I'm one of the other maintainers, and in agreement :+1:

**Comment by krisfrenette** [comment]
I am one of the maintainers and am in agreement 👍

**Comment by hunse** [comment]
Me too :+1:

**Comment by Carreau** [comment]
Welcome to the party !

**Pull request merged**
