### PR TITLE
[WIP] add the Common Workflow Language project

### PR DESCRIPTION
**Pull request by mr-c**
Please don't merge yet, pending review from the CWL reference implementation contributors

### CODE REVIEW

**Comment by Carreau** [comment]
Feel free to move the logo higher, we are roughly ordering things by popularity and use GitHub stars as a proxy. 

You might want to read the [practicalities](http://www.python3statement.org/practicalities/) section. In particular if you set `requires_python` in `setup.py` (or any other way to set the right metadata) a Python2 only version will not be installed on Python 2 and pip will grab only the latest compatible version, so Python 2 users should not even realize there is a new version.

**Comment by takluyver** [comment]
Thanks for the interest, but it doesn't look like CWL even supports Python 3 yet, so it's probably not practical for it to plan on dropping Python 2 support.

Feel free to ping us if there are any sticking points with Python 3 support - we have quite a bit of experience of updating code to add Python 3 support without breaking it for Python 2.

**Comment by mr-c** [comment]
@takluyver Our Google Summer of Code mentee is working on py3 support as I write this :-)

**Comment by mr-c** [comment]
To clarify, the CWL standards don't support lack support for Py3, we support any POSIX command line tool -- the CWL reference implementation itself is another story :-P

**Comment by takluyver** [comment]
I'm going to close this one to clean things up a bit. It looks like CWL supports Python 3 now. If there's a plan to drop Python 2 support, it's probably easiest to open a new pull request rather than resurrecting this.

**Pull request closed without merging**
