### PR TITLE
 Adding SaltStack

### PR DESCRIPTION
**Pull request by garethgreenaway**
SaltStack will not be supporting Python 2.x as of January 1, 2020 --and, at the time of this post, had over 9,800 stars on GitHub. Happy to adjust placement in the list!

### CODE REVIEW

**Comment by thatch45** [comment]
Hi, as the creator of Salt, I approve this pull request :)

**Comment by takluyver** [comment]
Thanks!

It looks like there are several other active maintainers now - are they on board with putting Salt's name on this? I'm not doubting you, we just try to make sure that no-one gets a surprised by a project they feel part of signing the statement.

**Comment by Ch3LL** [comment]
:+1:  from me

**Comment by garethgreenaway** [comment]
@takluyver I am a member of the SaltStack core team that is responsible for maintaining the Salt project, I've also asked other members of the team to comment on this. 🙂 We've also had a lengthy discussion with our community about dropping support for python 2 and the community is on board.

**Comment by waynew** [comment]
👍 Yes indeed! Python 2 was a great language that made the world a better place, but Python 3 is even better, and it's time for new versions of SaltStack to go Python3 only ❤️ 🚀 🌔

✨ 🐍 ✨

**Comment by s0undt3ch** [comment]
:+1: 
Long Live Python 3!

**Comment by twangboy** [comment]
Python 2 has been great, but it's time to move on.

**Comment by thatch45** [comment]
This move has been proposed and ratified by the SaltStack core engineering team and community in a Salt Enhancement Proposal:
https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0005-retire-py2-support.md

All deprecation warnings have been added to released software and release notes have made these announcements.
I appreciate your diligence in making sure we are all on board here!

**Comment by Carreau** [comment]
Thanks ! 

Make sure to look at the [practicalities page](https://python3statement.org/) and in  particular how to put `python_requires` in your setup.py, to make sure pip does not try to install newer versions of salt on old python. After all we still care about Python 2 users as many are stuck there, and would still like `pip install` to work form them !

**Comment by takluyver** [comment]
Thanks all, I think it looks like there's a clear consensus. :-)

**Pull request merged**
