### PR TITLE
Add ADB-Enhanced project

### PR DESCRIPTION
**Pull request by ashishb**
Add ADB-Enhanced project

### CODE REVIEW

**Comment by mscuthbert** [comment]
Confirmed committer is principal developer for project and project's Python 3.0 timeline is on the site.

**Comment by Carreau** [comment]
Awesome ! And welcome  !

Don't forget to read the [practicalities](https://python3statement.org/practicalities/) section to know how to add the `python_require` metadata for pip to understand the Python requirements !

**Comment by Carreau** [comment]
sounds good ! Feel free to ping us to review the PR !

**Comment by ashishb** [comment]
Definitely

**Pull request merged**
