### PR TITLE
Add PyMC3 to list of participating projects

### PR DESCRIPTION
**Pull request by fonnesbeck**

### CODE REVIEW

**Comment by Carreau** [comment]
Sweet ! Thanks ! Do you want to crosslink here where the discussion for that took place ? That would be useful for  user that stumble upon this issue.

**Comment by fonnesbeck** [comment]
This was discussed earlier today at our [monthly project meeting](https://github.com/pymc-devs/pymc3/wiki/PyMC-Project-Meetings), where we agreed that the PyMC3 project should commit to sunsetting our Python 2. support.

**Comment by fonnesbeck** [comment]
Let me know if you need the logo resized.

**Comment by Carreau** [comment]
> Let me know if you need the logo resized.

Nah, I think it looks fine when running locally!
Merging !

**Comment by Carreau** [comment]
Thanks ! Don't forget to look at the [practicalities page](http://www.python3statement.org/practicalities/) when stopping support and add your own experience !

**Pull request merged**
