### PR TITLE
Add Cantor

### PR DESCRIPTION
**Pull request by filipesaraiva**
If you're adding a project to the Python 3 statement, please ensure you have:

- [x] Discussed dropping Python 2 support with all maintainers
- [x] Discussed signing the statement with all maintainers

About the 2 points above, see [this commit](https://invent.kde.org/kde/cantor/-/commit/a0c253489e34cfb68b1a42cf0ebf2d89d6adf3a2) in Cantor repository at KDE Invent.

- [x] Added a suitable logo if the project has one
  - [x] Approximately square logos generally fit better than banners
  - [x] Compressed the logo to save bandwidth (run `scripts/squash-images.sh` on it)
- [x] Checked the Netlify preview made from the pull request

### CODE REVIEW

**Comment by takluyver** [comment]
@Carreau @tacaswell @asmeurer - how do we feel about adding new projects to the statement? I had kind of thought it was complete once we hit 2020, but we never updated the page to say so, and I don't think there's any harm in adding new projects now.

**Comment by hugovk** [comment]
This project got a shoutout from the 2.7 release manager in the final 2.7.18 release announcement:

> Python 3 would be nowhere without the critical work of the wider community. Library
maintainers followed CPython by maintaining Python 2 support for many years but also threw
their weight behind the Python 3 statement (https://python3statement.org). Linux distributors
chased Python 2 out of their archives. Users migrated hundreds of millions of lines of
code, developed porting guides, and kept Python 2 in their brain while Python 3 gained 10
years of improvements.

https://mail.python.org/archives/list/python-dev@python.org/thread/OFCIETIXLX34X7FVK5B5WPZH22HXV342/#OFCIETIXLX34X7FVK5B5WPZH22HXV342

This project definitely helped, thanks to everyone involved!

**Comment by Carreau** [comment]
> how do we feel about adding new projects to the statement? I had kind of thought it was complete once we hit 2020, but we never updated the page to say so, and I don't think there's any harm in adding new projects now.

I'm ok with that as well, the project says "drop support for Python 2.7 no later than 2020" and we are still in 2020, so project still have 6 month ? We can update the language slightly and I would also keep pointing to resource and guideline into staying up to data with Python version ([NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)) as a guideline as to what some community project are doing.

A note that the project is now under less maintenance and the we may not renew domain/hosting...

> This project got a shoutout from the 2.7 release manager in the final 2.7.18 release announcement:

Whooo ! Happy it had it effect, time to write a "python4statement" :-)

**Comment by mscuthbert** [comment]
While no site can be renewed forever, drop me a note if $$ is an issue for domain renewal costs -- happy to help keep it going for a few more years; at least till MacOS is shipping with Python 3.

**Comment by takluyver** [comment]
Thanks @mscuthbert . I believe @asmeurer has been kindly paying for the domain out of his own pocket so far. Its current registration runs until November. Aaron, thank-you, and please speak up if you want to stop paying it yourself, or split the bill.

Anyway, it sounds like we're happy to keep adding projects, and this looks good to me, so in it goes.

If anyone has a bright idea how to nicely rank non-Github projects (such as Cantor), please open an issue about it.

**Pull request merged**
