### PR TITLE
Add NumPy

### PR DESCRIPTION
**Pull request by njsmith**
See: https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

I would really like to include some kind of timeline information, and
perhaps a link to the above document, but I couldn't figure out how.
Any suggestions? The timeline seems to assume that you can predict all
your release dates and version numbers years in advance...

### CODE REVIEW

**Comment by Carreau** [comment]
> I would really like to include some kind of timeline information, and
> perhaps a link to the above document, but I couldn't figure out how.
> Any suggestions? The timeline seems to assume that you can predict all
> your release dates and version numbers years in advance...

I'm not sure how to have a gant chart with a not-really precise dates. What I can suggest  is to replace the version number by some text. like "new major versions Py3 Only" and "Long term support Python2"

Is that ok if I merge this and we see the timeline later ?

**Comment by Carreau** [comment]
Something like that:

screen shot 2017-11-14 at 21 18 05
```
'Numpy':[
      {content: 'all NumPy releases fully support Py2 and Py3', start: '2017-01-01', end:'2018-12-31', py2:true},
      {content: ' New NumPy releases are Python3 only', start: '2019-01-01', end:'2022-01-01'},
    ],
```

**Comment by njsmith** [comment]
Hmm, on further though, what do you think of something like:
```
'NumPy': [
    {content: '1.(x-1)', start: '2018-04-01', end: '2018-10-01', py2: true},
    {content: '1.x (last release in 2018)', start: '2018-10-01', end: '2019-12-31', py2: true},
    {content: '1.(x+1) (first release in 2019)', start: '2019-04-01', end: '2019-10-01'},
    {content: '1.(x+2)', start: '2019-10-01', end: '2020-04-01'},
    {content: '1.(x+3)', start: '2020-04-01', end: '2020-10-01'},
]
```

**Comment by njsmith** [comment]
The actual dates there are made up of course, but I guess that's true of all the entries on the chart :-)

**Comment by takluyver** [comment]
Thanks @njsmith . I'm going to merge this now - we can add timeline information later if you like.

I'd probably do the timeline for numpy with one bar saying 'Python 2 community support' to the end of 2019, and one saying 'New releases require Python 3' from the start of 2018.

**Comment by Carreau** [comment]
> Hmm, on further though, what do you think of something like:

Either are fine. I'm amazed by the positive/no-reaction reception on reddit/HN.

**Pull request merged**
