### PR TITLE
Adds Apache Beam to the list of participating projects.

### PR DESCRIPTION
**Pull request by tvalentyn**
If you're adding a project to the Python 3 statement, please ensure you have:

- [x] Discussed dropping Python 2 support with all maintainers. 
- [x] Discussed signing the statement with all maintainers. See: [voting thread](https://lists.apache.org/thread.html/634f7346b607e779622d0437ed0eca783f474dea8976adf41556845b@%3Cdev.beam.apache.org%3E) for links to discussion and vote result.
- [x] Added a suitable logo if the project has one
  - [x] Approximately square logos generally fit better than banners
  - [x] Compressed the logo to save bandwidth (run `scripts/squash-images.sh` on it)
- [x] Checked the Netlify preview made from the pull request

### CODE REVIEW

**Comment by tvalentyn** [comment]
Thanks a lot for setting up and maintaining python3statement.org! 
Do I have to add the autogenerated sg links in this pull request? If so, are there instructions somewhere? Our code lives at: https://github.com/apache/beam.

**Comment by takluyver** [comment]
Thanks! As you're linking to a non-Github site, I think it would be helpful if you could manually add the comment with the Github URL - there's a script which can use this to update the star counts and rearrange projects.

**Comment by tvalentyn** [comment]
Done, thanks.
I got "API rate limit exceeded" when running the scripts, so I did not update counters for other projects in this PR.

**Comment by takluyver** [comment]
Thanks. You don't need to run the star-count scripts as part of adding a project. :)

**Pull request merged**
