### PR TITLE
Biopython pledges to drop Python 2 support in or before 2020.

### PR DESCRIPTION
**Pull request by peterjc**
See https://github.com/biopython/biopython/commit/054f9c617eab2d3f46f7dcff3e2b5f224a1835b9

Note I have not seen the rendering of this change - please let me know if you need eg a smaller logo.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, and welcome aboard! Hopefully the logo should work nicely - I'm going to merge it and find out.

**Comment by Carreau** [comment]
Welcome ! And thanks for the pull request ! Don't forget to look at the [practicalities](http://www.python3statement.org/practicalities/) page, and feel free to add anything that you feel is missing !

Also side questions are the snakes head on the logo 3' or 5' ?

**Comment by peterjc** [comment]
Thank you both - the logo looks good on http://www.python3statement.org/ - I don't recall if we ever discussed if the tail/head orientation of the logo snakes specifically match the conventional DNA ordering from 3' to 5', maybe something to add to http://biopython.org/wiki/Logo ?

I've looked over the practicalities page, and noted we don't yet recommend updating pip and setuptools (indeed we have only just moved over to providing wheels with Biopython 1.70 and recommending pip).

**Comment by Carreau** [comment]
> I've looked over the practicalities page, and noted we don't yet recommend updating pip and setuptools (indeed we have only just moved over to providing wheels with Biopython 1.70 and recommending pip).

I would suggest looking on [bigquerry with a request like this one](https://bigquery.cloud.google.com/savedquery/420132102859:52f63ad110b4409fa7de6b85c1a0cffc) to see the number of download for each version of pip. In above link I do not filter by python version, but what would (likely) matter is the number of pip < 9 user on Python 2.

Here is what we got for IPython:

download

First dashed line is release of IPython 6.0, and you can see that a large number of "old pip" user downloaded IPython 6, on Python 2, and the installation failed with a clear error message that they need to upgrade pip (or pin IPython). If you draw this graph, the less orange users you have by the time you release the less problem you will potentially have. 

Note that you won't see all your old pip users as if they have the latest pip will  just says:
"No new versions available" and it wont count on the download page. 

Second dash line is release of 5.4 and 6.1, lighter gray line is when `requests` broke for a couple of hours.

**Comment by peterjc** [comment]
That's intriguing - I've not used Google's BigQuery before - thanks! Is it easy to show how to get your graph?

I've found some other illuminating examples like https://langui.sh/2016/12/09/data-driven-decisions/ and https://gist.github.com/juanpabloaj/dffc6900f80abcfe8ce121a39cffa743 which produces much simpler graphs. 

It looks like over the last year most of our PyPI downloads are via pip (ignoring things like the bandersnatch PyPI mirror tool). There were 215,971 pip downloads of which only 28.8% were for Python 3:

```
SELECT
  ROUND(100 * SUM(CASE WHEN REGEXP_EXTRACT(details.python, r"^([^\.]+)") = "3" THEN 1 ELSE 0 END) / COUNT(*), 1) AS percent_3,
  COUNT(*) as download_count,
FROM
  TABLE_DATE_RANGE(
    [the-psf:pypi.downloads],
    DATE_ADD(CURRENT_TIMESTAMP(), -365, "day"),
    DATE_ADD(CURRENT_TIMESTAMP(), -1, "day")
  )
WHERE
  file.project = 'biopython'
  AND details.installer.name == 'pip'
ORDER BY
  download_count DESC
LIMIT 100
```

**Comment by Carreau** [comment]
> Is it easy to show how to get your graph?

Yes, you can have a look [here](https://github.com/Carreau/talks/blob/master/2017-08-13-pybay/IPython-dls_2.ipynb) I'm still working on it, so the code is ugly.  I'm giving a talk in ~10 days at PyBay about that and I'm still churning through the data and thinking about the best graph to show, and the one that are interesting. 

For IPython we are at 34.6% for the past year, 42.7% over the past month. What is important is also how many of your Python 2 user have old pip vs new pip. And you also have to wonder how many users have pinned version. I know we still have users that stuck with IPython 4, as it is still using readline by default. SO I believe it is more complex than just looking at the % of users on which Python :-)

**Comment by peterjc** [comment]
Thanks for the link, and good luck for your talk.

I can see why the number of Python 2 users with an old version of pip will be quite important once we prepare to drop Python 2 support.

You've given me (us) lots to think about - thank you!

**Comment by Carreau** [comment]
So small update (while I'm preparing my talks). [here](https://github.com/Carreau/talks/blob/4481479af45f669534805d4ae2b5baf55001c7a7/2017-08-13-pybay/4-pip-breakdown.png) isa graph of the pip breakdown through time for IPython. 

4-pip-breakdown


You see that before release we are at about 65% new pip (I queried PyPI on a month of data before release). When we release there is a sharp decrease to ~45% for a week. My guess is that's because most of `pip install --upgrade` on systems that **already** have IPython install do not download a new version and thus do not count in the PyPI database count. 

The second thing, is: we did not tell our users how to pin IPython in the error message in case they can't upgrade pip. Thus I _think_ many pinned with `ipython==5.3` instead of `ipython<6`, which lead to a chuck not upgrading once 5.4 was released:

6-minor_download_do_5x_pin

(Orange: 6.0/6.1, Blue: 5.3/5.4)

**Comment by peterjc** [comment]
Thank you - beautiful graphs with an interesting story to tell. I hope we can read your slides after the talk, which together with the notebook https://github.com/Carreau/talks/blob/master/2017-08-13-pybay/IPython-dls_2.ipynb ought to be of interest to many project developers.

**Pull request merged**
