### PR TITLE
PyMeasure version schedule update

### PR DESCRIPTION
**Pull request by cjermain**
This PR updates the version schedule for the PyMeasure package.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks. Does it make sense to remove the 0.2 and 0.3 blocks now? On my laptop they're so narrow that I can only see '0.' on each.

**Comment by cjermain** [comment]
@takluyver, thanks for the suggestions. I've dropped those version and fixed a mistake on v0.6. The deploy preview looks good to me.

**Comment by takluyver** [comment]
Thanks!

**Comment by cjermain** [comment]
Thanks @takluyver!

**Pull request merged**
