### PR TITLE
Fixed multiple small issues in the practicalities

### PR DESCRIPTION
**Pull request by flying-sheep**
* A few syntax errors
* “ficticious”, not “fiction”
* Unified version bound representation (neither “x >1”, nor “x `>1`”, but “x > 1”)
* Made regex multiline for people to understand it.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks @flying-sheep ! I'm going to merge this and see how the ≥ symbols look in the webpage - I may want to revert to >= if they're note noticeable enough.

**Comment by takluyver** [comment]
This looks OK to me.

screenshot from 2017-04-20 14-59-42

**Comment by flying-sheep** [comment]
great!

**Comment by flying-sheep** [comment]
maybe you can configure smartypants to do this for you. “>=” in non-code honestly looks like weird ASCII art to me.

**Pull request merged**
