### PR TITLE
Signing the python3 statement for Altair

### PR DESCRIPTION
**Pull request by ellisonbg**
cc @jakevdp

### CODE REVIEW

**Comment by Carreau** [comment]
You will need a logo at some point :-P I'll let this wait a few hours to give a chance for Jake to +1 !

Thanks !

**Comment by jakevdp** [comment]
:+1:

**Comment by takluyver** [comment]
We're roughly sorting the project by prominence, using Github stars as a proxy (so far, all the projects listed are on Github). By this metric, altair can go between QIIME and gala.

**Comment by Carreau** [comment]
> We're roughly sorting the project by prominence, using Github stars as a proxy (so far, all the projects listed are on Github). By this metric, altair can go between QIIME and gala.

I can merge and move it up by hand.

**Pull request merged**
