### PR TITLE
Add axelrod to list

### PR DESCRIPTION
**Pull request by drvinceknight**
- Include logo
- Include md

We have not decided on version number for dropping py2 support but we
will be dropping it on the 1st of December. Do you have a suggested way forward?

### CODE REVIEW

**Comment by brettcannon** [comment]
If you're asking in regards to the timeline, you can probably just leave that out for now and add back in the version details later (panda, for instance, just landed and they just have their name and logo on the site ATM).

**Comment by drvinceknight** [comment]
Sorry, I wasn't very clear. Yes that's what I meant so leaving the timeline for now sounds good to me. :) :+1:

**Comment by asmeurer** [comment]
Yeah, the timeline is problematic, because it only really applies to projects that have planned release cycles. Let us know if you have any suggestions on how to format that better. It would be nice to have information like "axelrod plans to drop support on December 1st" on the page in some form for each project. SymPy is similar (our policy is to drop support for every version of Python, including 2.7, once it leaves security EOL, but we don't have a planned or even regular release cycle). Maybe the projects should have some kind of popover that could have a short blurb for each one describing what they plan to do.

**Comment by takluyver** [comment]
The timeline's also problematic because it's getting big. It's not a great format for displaying as much info as we're already trying to put into it. #46 is tracking that, if anyone wants to discuss possible alternative ways to display that info.

@drvinceknight We put projects in rough order of prominence, using Github stars as a proxy measure. By that metric, feel free to insert axelrod just after PyStan. Thanks :-)

**Comment by drvinceknight** [comment]
> By that metric, feel free to insert axelrod just after PyStan.

Done (7d591d4). Thanks :) 👍

**Pull request merged**
