### PR TITLE
Add Rdkit

### LINKED ISSUE #80: Add RDKit to list of projects
The RDKit is an open-source cheminformatics toolkit that has had Python 3 support for several years and has recently committed to move over completely to Python 3 by 2020:
http://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg06935.html

Here's the text:
```- [RDKit](https://github.com/rdkit/rdkit)```

and the logo:
rdkit 64

And the timeline (hopefully I got this right):
```
'RDKit':[
	    {content: '2014.9.1 - 2019.03.1', start: '2014-09-1', end: '2019-09-1', py2:true},
	    {content: '2019.9.1 -' , start: '2019-09-01', end: '2021-03-01'}
	    ]
```

### PR DESCRIPTION
**Pull request by Carreau**
Closes #80

### CODE REVIEW

**Comment by greglandrum** [comment]
Thanks!

**Comment by takluyver** [comment]
:-) Welcome aboard!

**Comment by greglandrum** [comment]
Thanks for organizing thiseffort.
It's great to have a public forcing function on the Python3 switch.
I'm *really* looking forward to being able to deprecate Python 2.

**Comment by Carreau** [comment]
> It's great to have a public forcing function on the Python3 switch.
> I'm really looking forward to being able to deprecate Python 2.

We'll be happy if you can look at the practicalities section and contribute to it to help others make and even more painless transition. http://www.python3statement.org/practicalities/ 

Thanks !

**Pull request merged**
