### PR TITLE
Move software carpentry up a bit

### PR DESCRIPTION
**Pull request by Carreau**
As requested by @takluyver .

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
Hmm, that logo looks a bit odd amongst the others. Too tired to have any ideas what to do with it, though.

**Comment by brettcannon** [comment]
I think it's because the logo isn't vertically centered. Don't know what magic CSS you could do to fix that, though.

**Comment by Carreau** [comment]
> I think it's because the logo isn't vertically centered. Don't know what magic CSS you could do to fix that, though.

Yeah, without heavy refactoring of the html that's going to be hard even with css you need wrapper html elements, and we'd like to keep markdown that's going to be tough. 

Alternatively we can use another SWC logo , eg : 

this

Which looks better:

screen shot 2016-11-21 at 15 45 33

As it has an aspect ratio closer to 1.

(need to remove the drop shadow though)

**Comment by takluyver** [comment]
+1 for the two-line version of the logo, if someone has a moment to switch it.

**Pull request merged**
