### PR TITLE
Add pandas

### PR DESCRIPTION
**Pull request by takluyver**
See pydata/pandas-design#5

Here's what it looks like, using the right-hand part of the pandas logo:
screenshot from 2016-09-15 15-11-19

### CODE REVIEW

**Comment by Carreau** [comment]
Great ! the PyPA pull request that make the DB layout efficient for `pypa/simple` is almost ready.

**Comment by takluyver** [comment]
There were no objections and plenty of enthusiasm for this on the pandas thread, so I've merged it as I indicated I would.

**Comment by brettcannon** [comment]
Great news!

I take it pandas hasn't come up with a timeline yet to add to the page?

**Comment by takluyver** [comment]
Pandas has not. The plan is to make a 'Pandas 2' which requires Python 3, and the current codebase will go into long-term support, like we're doing with IPython.

**Pull request merged**
