### PR TITLE
Add Software Carpentry

### PR DESCRIPTION
**Pull request by jduckles**
Sorry for the delay, you asked our project to sign this back in June and we approved it in July. Please add our signature at your convenience.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks @jduckles !

We're putting the logos in approximate order of prominence, which we've assessed until now based on Github stars. I'm not quite sure how we do that for SC, as it doesn't have a single main Github repo, but the deprecated bc repo still has 295 stars - that would put it between AstroPy and SunPy, if you want to move it up there.

I notice that some of the projects have gained stars since they were added that would lead them to move in the order. We may need to think a bit more about how we decide on the order, but that's a separate matter from this PR.

**Comment by Carreau** [comment]
Any opposition to merging and ordering later ? I can take care of changing ordering.

**Comment by takluyver** [comment]
That works for me, thanks Matthias.

@jduckles welcome on board :-)

**Comment by Carreau** [comment]
Thanks @jduckles !

@takluyver #58 should put swc a bit higher in the list.

**Pull request merged**
